apps/recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new/', views.RecipeCreateView.as_view(), name='new'),
    path('follow/', views.FollowView.as_view(), name='follow'),
    path('favorites/', views.FavoriteView.as_view(), name='favorites'),
    path('purchases/', views.PurchaseView.as_view(), name='purchases'),
    path(
        'purchases/download/',
        views.DownloadPurchasesListView.as_view(),
        name='purchases_download',
    ),
    path('<str:username>/', views.ProfileView.as_view(), name='profile'),
    path(
        '<str:username>/<int:pk>/',
        views.RecipeView.as_view(),
        name='recipe',
    ),
    path(
        '<str:username>/<int:pk>/edit/',
        views.RecipeUpdateView.as_view(),
        name='recipe_edit',
    ),
    path(
        '<str:username>/<int:pk>/delete/',
        views.RecipeDeleteView.as_view(),
        name='recipe_delete',
    )
]

foodgram/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import include, path

handler404 = 'foodgram.views.page_not_found'  # noqa
handler500 = 'foodgram.views.server_error'  # noqa


flatpages_urls = [
    path('pages/', include('django.contrib.flatpages.urls')),
    path('author/', views.flatpage, {'url': '/author/'}, name='about_author'),
    path('tech/', views.flatpage, {'url': '/tech/'}, name='about_tech'),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('apps.users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('api/', include('apps.api.urls')),
    path('about/', include(flatpages_urls)),
    path('', include('apps.recipes.urls', namespace='recipes')),
]


if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/recipes/models.py
from django.contrib.auth import get_user_model
from django.db import models
from .validation import validate_zero

User = get_user_model()


class Ingredient(models.Model):
    title = models.CharField(max_length=256, verbose_name="name")
    dimension = models.CharField(max_length=256, verbose_name="unit")

    class Meta:
        ordering = ("title",)
        verbose_name = "Ингредиент"
        verbose_name_plural = "Ингредиенты"
        constraints = [
            models.UniqueConstraint(
                fields=("title", "dimension"), name="unique_composition_link"
            ),
        ]

    def __str__(self):
        return f"{self.title}, {self.dimension}"


class Recipe(models.Model):
    title = models.CharField(max_length=256, verbose_name="name")
    author = models.ForeignKey(
        User,
        related_name="recipes",
        on_delete=models.CASCADE,
        verbose_name="author",
    )
    text = models.TextField(verbose_name="text")
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name="pub date")
    cooking_time = models.PositiveIntegerField(
        verbose_name="Cooking time", validators=[validate_zero]
    )
    ingredients = models.ManyToManyField(
        Ingredient, through="RecipeIngredient", verbose_name="ingredients"
    )
    tags = models.ManyToManyField(
        "Tag", blank=True, related_name="recipes", verbose_name="tags"
    )
    image = models.ImageField(
        blank=False, upload_to="recipes/", verbose_name="image"
    )

    class Meta:
        ordering = ("-pub_date",)
        verbose_name = "Рецепт"
        verbose_name_plural = "Рецепты"

    def __str__(self):
        return f"{self.title}"


class RecipeIngredient(models.Model):
    ingredient = models.ForeignKey(
        Ingredient, on_delete=models.CASCADE, verbose_name="ingredient"
    )
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, verbose_name="recipe"
    )
    quantity = models.PositiveIntegerField(verbose_name="value")

    class Meta:
        verbose_name = "Ингредиенты рецепта"
        verbose_name_plural = "Ингредиенты рецептов"


class TagChoices(models.TextChoices):
    BREAKFAST = "breakfast", "Завтрак"
    LUNCH = "lunch", "Обед"
    DINNER = "dinner", "Ужин"


class ColorChoices(models.TextChoices):
    GREEN = "green", "Зеленый"
    ORANGE = "orange", "Оранжевый"
    PURPLE = "purple", "Фиолетовый"


class Tag(models.Model):
    title = models.CharField(
        choices=TagChoices.choices,
        default=TagChoices.LUNCH,
        unique=True,
        max_length=10,
        verbose_name="title",
    )
    color = models.CharField(
        choices=ColorChoices.choices,
        default=ColorChoices.GREEN,
        unique=True,
        max_length=10,
        verbose_name="color",
    )

    class Meta:
        ordering = ("pk",)
        verbose_name = "Тег"
        verbose_name_plural = "Теги"

    def __str__(self):
        return self.title


class Favorite(models.Model):
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name="in_favorites",
        verbose_name="recipe",
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="favorite_recipes",
        verbose_name="user",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=("recipe", "user"), name="unique_favorite_recipe"
            )
        ]
        verbose_name = "Избранный"
        verbose_name_plural = "Избранные"

    def __str__(self):
        return f"{self.recipe.title} is {self.user.username} favorite"


class Purchase(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="purchases",
        verbose_name="user",
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name="in_purchases",
        verbose_name="recipe",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_purchase"
            ),
        ]
        verbose_name = "Покупка"
        verbose_name_plural = "Покупки"

    def __str__(self):
        return f"{self.user}, {self.recipe}"

templates/include/author_card.html
{% load user_filters %}

<div class="card-user" data-author="{{ author.pk }}">
    <div class="card-user__header">
        <h2 class="card-user__title">{{ author.get_full_name|default:author.username }} </h2>
    </div>
    <div class="card-user__body">
        <ul class="card-user__items">
            {% for recipe in author.recipes.all|slice:":3" %}
                <li class="card-user__item">
                    {% include 'include/recipe_preview.html' with recipe=recipe %}
                </li>
            {% endfor %}

            {% if author.recipes.count > 3 %}
                <li class="card-user__item">
                    <a href="{% url 'recipes:profile' username=author.username %}" class="card-user__link link">Еще {{ author.recipes.count|add:"-3"|declination:"" }} </a>
                </li>
            {% endif %}
        </ul>
    </div>
    <div class="card-user__footer">
        <button class="button button_style_light-blue button_size_auto" name="subscribe">Отписаться</button>
    </div>
</div>

templates/include/button_favorite.html
{% load user_filters %}

<div class="single-card__favorite">
<button class="button button_style_none" name="favorites"
  {% if not recipe|is_favorite:user %}
    data-out><span class="icon-favorite {% if big %}icon-favorite_big{% endif %}">
  {% else %}
    ><span class="icon-favorite icon-favorite_active {% if big %}icon-favorite_big{% endif %}">
  {% endif %}
    </span>
</button>
{% if big %}
  <div class="single-card__favorite-tooltip tooltip">Добавить в избранное</div>
{% endif %}
</div>

templates/include/button_purchase.html
{% load user_filters %}

{% if user.is_authenticated and recipe|is_purchase:user %}
    <button class="button button_style_light-blue-outline" name="purchases">
        <span class="icon-check button__icon"></span> Рецепт добавлен
    </button>
{% else %}
    <button class="button button_style_light-blue" name="purchases" data-out>
        <span class="icon-plus button__icon"></span>Добавить в покупки
    </button>
{% endif %}

templates/include/button_subscribe.html
{% load user_filters %}
{% url 'recipes:profile' username=author.username as url_profile %}

{% if user.is_authenticated and user != author %}
    {% if user|is_follower:author %}
        <button class="button button_style_light-blue button_size_subscribe" name="subscribe">
            Отписаться от автора
        </button>
    {% else %}
        <button class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>
            Подписаться на автора
        </button>
    {% endif %}
{% endif %}

templates/include/footer.html
<div class="footer__container container">
    <a href="{% url 'recipes:index' %}" class="footer__brand link">Продуктовый помощник</a>
    <ul class="footer__items">
        <li class="footer__item"><a href="{% url 'about_author' %}" class="footer__link link">Об авторе </a></li>
        <li class="footer__item"><a href="{% url 'about_tech' %}" class="footer__link link">Технологии</a></li>
    </ul>
</div>

templates/include/form_group.html
{% load user_filters %}

 <div class="form__group">
     <label for="{{ field.id_for_label }}" class="form__label">{{ field.label }}</label>
     <div class="form__field-group">
         {{ field|addclass:"form__input" }}

         {% if field.name == 'new_password1' %}
         <span class="form__input-info">Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</span>
         <span class="form__input-info">Ваш пароль должен содержать как минимум 8 символов.</span>
         <span class="form__input-info">Ваш пароль не может быть одним из широко распространённых паролей.</span>
         <span class="form__input-info">Ваш пароль не может состоять только из цифр.</span>
         {% endif %}

         {% if field.errors %}
         {% for error in field.errors %}
         <span class="form__error">{{ error|escape }}</span>
         {% endfor %}
         {% endif %}
     </div>
 </div>

templates/include/nav.html
{% load user_filters %}

<header class="header">
    <nav class="nav">
        <div class="nav__container container">
            {% with url=request.resolver_match.url_name %}
            <ul class="nav__items list">
                <li class="nav__item {% if url == 'index' %}nav__item_active{% endif %}"><a
                        href="{% url 'recipes:index' %}" class="nav__link link">Рецепты</a></li>
                {% if user.is_authenticated %}
                <li class="nav__item {% if url == 'follow' %}nav__item_active{% endif %}"><a
                        href="{% url 'recipes:follow' %}" class="nav__link link">Мои подписки</a></li>
                <li class="nav__item {% if url == 'new' %}nav__item_active{% endif %}"><a href="{% url 'recipes:new' %}"
                        class="nav__link link">Создать рецепт</a></li>
                <li class="nav__item {% if url == 'favorites' %}nav__item_active{% endif %}"><a
                        href="{% url 'recipes:favorites' %}" class="nav__link link">Избранное</a></li>
                {% endif %}
                <li
                    class="nav__item {% if user.is_anonymous %}nav__item_disabled{% elif url == 'purchases' %}nav__item_active{% endif %}">
                    <a href="{% url 'recipes:purchases' %}" class="nav__link link">
                        {% if user.is_authenticated %}
                        Список покупок
                        <span class="badge badge_style_blue nav__badge" id="counter">{% if get_purchases_count > 0 %}
                            {{ get_purchases_count }}{% endif %}</span>
                        {% endif %}
                    </a>
                </li>
            </ul>
            <ul class="nav__items list">
                {% if user.is_authenticated %}
                <li class="nav__item {% if url == 'password_change' %}nav__item_active{% endif %}"><a
                        href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a></li>
                <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Выход</a></li>
                {% else %}
                <li class="nav__item {% if url == 'login' %}nav__item_active{% endif %}"><a href="{% url 'login' %}"
                        class="nav__link link">Войти</a></li>
                <li class="nav__item"><a href="{% url 'signup' %}" class="button button_style_blue">Создать аккаунт</a>
                </li>
                {% endif %}
            </ul>
            {% endwith %}
        </div>
    </nav>
</header>

templates/include/paginator.html
{% load user_filters %}

<nav class="pagination" aria-label="Search results pages">

    <ul class="pagination__container">

        {% if page.has_previous %}
            <li class="pagination__item"><a class="pagination__link link" href="{% full_page request page.previous_page_number %}"><span class="icon-left"></span></a></li>
        {% endif %}

        {% for page_number in paginator.page_range %}

            {% if page.number == page_number %}
                <li class="pagination__item pagination__item_active"><a class="pagination__link link">{{ page_number }}</a></li>
            {% else %}
                <li class="pagination__item"><a class="pagination__link link" href="{% full_page request page_number %}">{{ page_number }}</a></li>
            {% endif %}

        {% endfor %}

        {% if page.has_next %}
            <li class="pagination__item"><a class="pagination__link link" href="{% full_page request page.next_page_number %}"><span class="icon-right"></span></a></li>
        {% endif %}

    </ul>
</nav>

templates/include/recipe_card.html
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static 'pages/single.css' %}">{% endblock css %}

<div class="card" data-id="{{ recipe.pk }}">
    <a href="{% url 'recipes:recipe' username=recipe.author.username pk=recipe.id %}" class="link" target="_blank">
        {% load thumbnail %}
        {% thumbnail recipe.image "364x240" crop="center" upscale=True as im %}
            <img src="{{ im.url }}" alt="{{ recipe.title }}" class="card__image">
        {% endthumbnail %}
    </a>
    <div class="card__body">
        <a class="card__title link" href="{% url 'recipes:recipe' username=recipe.author.username pk=recipe.id %}" target="_blank">{{ recipe.title }}</a>
        <ul class="card__items">
            {% for tag in recipe.tags.all %}
                <li class="card__item"><span class="badge badge_style_{{ tag.color }}">{{ tag.get_title_display }}</span></li>
            {% endfor %}
        </ul>
        <div class="card__items card__items_column">
            <p class="card__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
            <p class="card__text"><span class="icon-user"></span> 
                <a href="{% url 'recipes:profile' username=recipe.author.username %}" style="color: black">{{ recipe.author.get_full_name|default:recipe.author.username }}</a>
            </p>
        </div>
    </div>
    {% if user.is_authenticated %}
        <div class="card__footer">
            {% include 'include/button_purchase.html' %}
            {% include 'include/button_favorite.html' %}
        </div>
    {% endif %}
</div>

templates/include/recipe_preview.html
{% load thumbnail %}

<div class="recipe">
    {% thumbnail recipe.image "500x500" crop="center" upscale=False as im %}
        <img src="{{ im.url }}" alt="{{ recipe.name }}" class="recipe__image">
    {% endthumbnail %}
    <h3 class="recipe__title">{{ recipe.title }}</h3>
    <p class="recipe__text"><span class="icon-time"></span> <small>{{ recipe.cooking_time }} мин.</small></p>
</div>

templates/include/recipe_purchases_preview.html
{% load thumbnail %}

<li class="shopping-list__item" data-id="{{ recipe.pk }}">
    <div class="recipe recipe_reverse">
        {% thumbnail recipe.image "500x500" crop="center" upscale=False as im %}
            <img src="{{ im.url }}" alt="{{ recipe.title }}" class="recipe__image recipe__image_big">
        {% endthumbnail %}
        <h3 class="recipe__title">{{ recipe.title }}</h3>
        <p class="recipe__text"><span class="icon-time"></span> <small>{{ recipe.cooking_time }} мин.</small></p>
    </div>
    <a href="#" class="shopping-list__button link">Удалить</a>
</li>

templates/include/tags.html
{% load user_filters %}
<ul class="tags">
    {% for tag in tags %}
        <li class="tags__item">
            <a id="{{ tag.title }}"
                class="tags__checkbox tags__checkbox_style_{{ tag.color }} {% if tag.title in active_tags %} tags__checkbox_active {% endif %}"
                href="?{% manage_tags tag=tag.title %}">
            </a>
            <span class="tags__label">{{ tag.get_title_display }}</span>
        </li>
    {% endfor %}
</ul>