apps/recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('new/', views.RecipeCreateView.as_view(), name='new'),
    path('follow/', views.FollowView.as_view(), name='follow'),
    path('favorites/', views.FavoriteView.as_view(), name='favorites'),
    path('purchases/', views.PurchaseView.as_view(), name='purchases'),
    path(
        'purchases/download/',
        views.DownloadPurchasesListView.as_view(),
        name='purchases_download',
    ),
    path('<str:username>/', views.ProfileView.as_view(), name='profile'),
    path(
        '<str:username>/<int:pk>/',
        views.RecipeView.as_view(),
        name='recipe',
    ),
    path(
        '<str:username>/<int:pk>/edit/',
        views.RecipeUpdateView.as_view(),
        name='recipe_edit',
    ),
    path(
        '<str:username>/<int:pk>/delete/',
        views.RecipeDeleteView.as_view(),
        name='recipe_delete',
    )
]

foodgram/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import include, path

handler404 = 'foodgram.views.page_not_found'  # noqa
handler500 = 'foodgram.views.server_error'  # noqa


flatpages_urls = [
    path('pages/', include('django.contrib.flatpages.urls')),
    path('author/', views.flatpage, {'url': '/author/'}, name='about_author'),
    path('tech/', views.flatpage, {'url': '/tech/'}, name='about_tech'),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('apps.users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('api/', include('apps.api.urls')),
    path('about/', include(flatpages_urls)),
    path('', include('apps.recipes.urls', namespace='recipes')),
]


if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/recipes/models.py
from django.contrib.auth import get_user_model
from django.db import models
from .validation import validate_zero

User = get_user_model()


class Ingredient(models.Model):
    title = models.CharField(max_length=256, verbose_name="name")
    dimension = models.CharField(max_length=256, verbose_name="unit")

    class Meta:
        ordering = ("title",)
        verbose_name = "Ингредиент"
        verbose_name_plural = "Ингредиенты"
        constraints = [
            models.UniqueConstraint(
                fields=("title", "dimension"), name="unique_composition_link"
            ),
        ]

    def __str__(self):
        return f"{self.title}, {self.dimension}"


class Recipe(models.Model):
    title = models.CharField(max_length=256, verbose_name="name")
    author = models.ForeignKey(
        User,
        related_name="recipes",
        on_delete=models.CASCADE,
        verbose_name="author",
    )
    text = models.TextField(verbose_name="text")
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name="pub date")
    cooking_time = models.PositiveIntegerField(
        verbose_name="Cooking time", validators=[validate_zero]
    )
    ingredients = models.ManyToManyField(
        Ingredient, through="RecipeIngredient", verbose_name="ingredients"
    )
    tags = models.ManyToManyField(
        "Tag", blank=True, related_name="recipes", verbose_name="tags"
    )
    image = models.ImageField(
        blank=False, upload_to="recipes/", verbose_name="image"
    )

    class Meta:
        ordering = ("-pub_date",)
        verbose_name = "Рецепт"
        verbose_name_plural = "Рецепты"

    def __str__(self):
        return f"{self.title}"


class RecipeIngredient(models.Model):
    ingredient = models.ForeignKey(
        Ingredient, on_delete=models.CASCADE, verbose_name="ingredient"
    )
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, verbose_name="recipe"
    )
    quantity = models.PositiveIntegerField(verbose_name="value")

    class Meta:
        verbose_name = "Ингредиенты рецепта"
        verbose_name_plural = "Ингредиенты рецептов"


class TagChoices(models.TextChoices):
    BREAKFAST = "breakfast", "Завтрак"
    LUNCH = "lunch", "Обед"
    DINNER = "dinner", "Ужин"


class ColorChoices(models.TextChoices):
    GREEN = "green", "Зеленый"
    ORANGE = "orange", "Оранжевый"
    PURPLE = "purple", "Фиолетовый"


class Tag(models.Model):
    title = models.CharField(
        choices=TagChoices.choices,
        default=TagChoices.LUNCH,
        unique=True,
        max_length=10,
        verbose_name="title",
    )
    color = models.CharField(
        choices=ColorChoices.choices,
        default=ColorChoices.GREEN,
        unique=True,
        max_length=10,
        verbose_name="color",
    )

    class Meta:
        ordering = ("pk",)
        verbose_name = "Тег"
        verbose_name_plural = "Теги"

    def __str__(self):
        return self.title


class Favorite(models.Model):
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name="in_favorites",
        verbose_name="recipe",
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="favorite_recipes",
        verbose_name="user",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=("recipe", "user"), name="unique_favorite_recipe"
            )
        ]
        verbose_name = "Избранный"
        verbose_name_plural = "Избранные"

    def __str__(self):
        return f"{self.recipe.title} is {self.user.username} favorite"


class Purchase(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="purchases",
        verbose_name="user",
    )
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name="in_purchases",
        verbose_name="recipe",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_purchase"
            ),
        ]
        verbose_name = "Покупка"
        verbose_name_plural = "Покупки"

    def __str__(self):
        return f"{self.user}, {self.recipe}"

apps/recipes/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Ingredient, Recipe, Tag
from .service import add_ingredients_to_recipe


class RecipeForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        label="Теги",
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    ingredients = forms.CharField(
        required=False,
        label="Ингредиенты",
        widget=forms.TextInput(attrs={"id": "nameIngredient"}),
    )

    class Meta:
        model = Recipe
        fields = (
            "title",
            "tags",
            "ingredients",
            "cooking_time",
            "text",
            "image",
        )
        labels = {
            "title": "Название рецепта",
            "text": "Рецепт",
            "cooking_time": "Время приготовления",
            "image": "Загрузить фото",
        }
        widgets = {
            "cooking_time": forms.TextInput(),
        }

        error_messages = {
            'cooking_time': {
                'min_value': '"Время приготовления" должно быть положительным',
            }
        }

    def clean_ingredients(self):
        ingredients = list(
            zip(
                self.data.getlist("nameIngredient"),
                self.data.getlist("valueIngredient"),
            ),
        )

        if not ingredients:
            raise forms.ValidationError("Отсутствуют ингредиенты")

        all_ingredients = Ingredient.objects.all()
        ingredients_clean = []
        for name, quantity in ingredients:
            if not all_ingredients.filter(title=name):
                raise ValidationError(
                    f'В базе данных нет ингредиента "{name}".'
                )
            if int(quantity) < 1:
                raise forms.ValidationError(
                    f'Исправьте количество ингредиента "{name}"'
                )
            else:
                ingredients_clean.append(
                    {
                        "title": name,
                        "quantity": quantity,
                    }
                )
        return ingredients_clean

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.save()
        ingredients = self.cleaned_data["ingredients"]
        self.cleaned_data["ingredients"] = []
        self.save_m2m()
        add_ingredients_to_recipe(self.instance, ingredients)

        return instance

apps/recipes/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Exists, OuterRef
from django.http import FileResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView, View)
from django_filters.views import BaseFilterView

from foodgram import settings

from .filters import TaggedRecipeFilterSet
from .forms import RecipeForm
from .mixins import TagContextMixin
from .models import Favorite, Purchase, Recipe
from .permissions import AdminAuthorPermission
from .service import generate_pdf

User = get_user_model()


class IndexView(TagContextMixin, BaseFilterView, ListView):
    model = Recipe
    template_name = 'recipes/index.html'
    paginate_by = settings.PAGINATE_BY
    filterset_class = TaggedRecipeFilterSet

    def get_queryset(self):
        queryset = super().get_queryset()

        if self.request.user.is_authenticated:
            queryset = queryset.annotate(
                is_favorites=Exists(
                    Favorite.objects.filter(
                        user=self.request.user,
                        recipe=OuterRef('pk'),
                    ),
                ),
            ).annotate(
                is_purchase=Exists(
                    Purchase.objects.filter(
                        user=self.request.user,
                        recipe=OuterRef('pk'),
                    ),
                ),
            )
        return queryset


class FollowView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'recipes/follow.html'
    paginate_by = settings.PAGINATE_BY
    queryset = User.objects.all()

    def get_queryset(self):
        return FollowView.queryset.filter(
            followers__user=self.request.user).order_by('-id')


class FavoriteView(TagContextMixin, LoginRequiredMixin,
                   BaseFilterView, ListView):
    model = Recipe
    template_name = 'recipes/favorites.html'
    paginate_by = settings.PAGINATE_BY
    filterset_class = TaggedRecipeFilterSet
    queryset = Recipe.objects.all()

    def get_queryset(self):
        return FavoriteView.queryset.filter(
            in_favorites__user=self.request.user)


class ProfileView(TagContextMixin, BaseFilterView, ListView):
    model = Recipe
    template_name = 'recipes/profile.html'
    paginate_by = settings.PAGINATE_BY
    filterset_class = TaggedRecipeFilterSet
    queryset = Recipe.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        author = get_object_or_404(User, username=self.kwargs['username'])
        is_follower = False
        if self.request.user.is_authenticated:
            is_follower = self.request.user.followers.filter(
                author=author).exists()
        context.update(
            {
                'user_is_follower': is_follower,
                'author': author,
            }
        )
        return context

    def get_queryset(self):
        author = get_object_or_404(User, username=self.kwargs['username'])
        return ProfileView.queryset.filter(author=author)


class RecipeView(DetailView):
    model = Recipe
    template_name = 'recipes/recipe.html'


class RecipeCreateView(LoginRequiredMixin, CreateView):
    model = Recipe
    template_name = 'recipes/add_recipe.html'
    form_class = RecipeForm
    success_url = reverse_lazy('recipes:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    permission_classes = AdminAuthorPermission
    template_name = 'recipes/add_recipe.html'
    form_class = RecipeForm
    success_url = reverse_lazy('recipes:index')


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    permission_classes = AdminAuthorPermission
    success_url = reverse_lazy('recipes:purchases')


class PurchaseView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'recipes/purchases.html'
    queryset = Recipe.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['object_list'] = self.get_user_purchase()
        return context

    def get_user_purchase(self):
        return PurchaseView.queryset.filter(
            in_purchases__user=self.request.user)


class DownloadPurchasesListView(View):
    def get(self, request, *args, **kwargs):
        pdf = generate_pdf(request.user)

        return FileResponse(
            pdf,
            as_attachment=True,
            filename='purchases.pdf',
        )


@login_required
def get_purchases_count(request):
    """
    Shopping List.
    """
    recipes = request.user.purchases.all()
    return render(
        request,
        {'recipes': recipes},
    )

templates/recipes/add_recipe.html
{% extends 'base.html' %}
{% load static %}
{% load user_filters %}

{% block title %}{% if recipe %}Редактирование рецепта{% else %}Создание рецепта{% endif %}{% endblock title %}
{% block css %}
<link rel="stylesheet" href="{% static 'pages/form.css' %}">{% endblock css %}

{% block header_title %}{% if recipe %}Редактирование рецепта{% else %}Создание рецепта{% endif %}{% endblock %}
{% block tags %}{% endblock tags %}
{% block content %}

<div class="form-container">
    <form class="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <div class="form__group">
            <label for="{{ field.id_for_label }}" class="form__label">{{ field.label }}</label>
            <div class="form__field-group {% if field.name == 'cooking_time' %}form__field-group_time{% endif %}">
                {% if field.name == 'tags' %}
                <div class="tags">
                    {% for tag in form.fields.tags.choices.queryset %}
                    <div class="tags__item">
                        <input type="checkbox" name="tags" value="{{ tag.pk }}" id="id_{{ tag.name }}"
                            class="tags__checkbox tags__checkbox_style_{{ tag.color }}" <label for="id_{{ tag.name }}"
                            class="tags__label">{{ tag.get_title_display }}</label>
                    </div>
                    {% endfor %}
                </div>
                {% elif field.name == 'ingredients' %}
                <div class="form__field-group-ingredientes">
                    <div class="form__dropdown">
                        <input type="text" id="nameIngredient" class="form__input">
                        <div class="form__dropdown-items"></div>
                    </div>
                    <input type="number" id="cantidad" class="form__input" min="0">
                    <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                </div>

                <div class="form__field-group-ingredientes-container">
                    {% if recipe %}
                    {% for ingredient in recipe.recipeingredient_set.all %}
                    <div class="form__field-item-ingredient" id="ing_{{ forloop.counter }}">
                        <span> {{ ingredient.ingredient.title }} {{ ingredient.quantity }}
                            {{ ingredient.ingredient.dimension }}</span>
                        <span class="form__field-item-delete"></span>
                        <input id="nameIngredient_{{ forloop.counter }}" name="nameIngredient" type="hidden"
                            value="{{ ingredient.ingredient.title }}">
                        <input id="valueIngredient_{{ forloop.counter }}" name="valueIngredient" type="hidden"
                            value="{{ ingredient.quantity }}">
                        <input id="unitsIngredient_{{ forloop.counter }}" name="unitsIngredient" type="hidden"
                            value="{{ ingredient.ingredient.dimension }}">
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>

                <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                {% elif field.name == 'text' %}
                {{ field|addclass:"form__textarea" }}
                {% elif field.name == 'cooking_time' %}
                {{ field|addclass:"form__input" }}
                <label for="id_time" class="form__label">минут</label>
                {% elif field.name == 'image' %}
                {{ field }}
                {% else %}
                {{ field|addclass:"form__input" }}
                {% endif %}

                {% if field.errors %}
                {% for error in field.errors %}
                <span class="form__error">{{ error|escape }}</span>
                {% endfor %}
                {% endif %}
            </div>
        </div>
        {% endfor %}
        <div class="form__footer">
            {% if recipe %}
            <button class="button button_style_blue">Сохранить</button>
            <a style="margin-left: 2.5em"
                href="{% url 'recipes:recipe_delete' username=recipe.author.username pk=recipe.pk %}"
                class="form__ingredient-link">Удалить</a>
            {% else %}
            <button class="button button_style_blue">Создать рецепт</button>
            {% endif %}
        </div>
    </form>
</div>
{% endblock content %}

{% block scripts %}
<script src="{% static 'js/utils/debouncing.js' %}"></script>
<script src="{% static 'formRecipe.js' %}"></script>
{% endblock scripts %}

templates/recipes/favorites.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Избранное{% endblock %}
{% block css %}<link rel="stylesheet" href="{% static 'pages/index.css' %}">{% endblock css %}

{% block header_title %}Избранное{% endblock header_title %}
{% block content %}
    <div class="card-list">
        {% for recipe in page_obj %}
            {% include 'include/recipe_card.html' with recipe=recipe %}
        {% endfor %}
    </div>

    {% if page_obj.has_other_pages %}
        {% include 'include/paginator.html' with page=page_obj paginator=paginator %}
    {% endif %}
{% endblock content %}

{% block scripts %}
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/CardList.js' %}"></script>
    <script src="{% static 'favorite.js' %}"></script>
{% endblock scripts %}

templates/recipes/follow.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Мои подписки{% endblock %}
{% block css %}<link rel="stylesheet" href="{% static 'pages/myFollow.css' %}">{% endblock css %}

{% block header_title %}Мои подписки{% endblock header_title %}
{% block tags %}{% endblock tags %}
{% block content %}
    <div class="card-list">
        {% for author in object_list %}
            {% include 'include/author_card.html' with author=author %}
        {% endfor %}
    </div>

    {% if page_obj.has_other_pages %}
        {% include 'include/paginator.html' with items=page_obj paginator=paginator %}
    {% endif %}
{% endblock content %}

{% block scripts %}
    <script src="{% static 'js/components/MyFollow.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'myFollow.js' %}"></script>
{% endblock scripts %}

templates/recipes/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="card-list">
        {% for recipe in page_obj %}
            {% include 'include/recipe_card.html' %}
        {% endfor %}
    </div>
    {% if page_obj.has_other_pages %}
        {% include 'include/paginator.html' with page=page_obj paginator=paginator%}
    {% endif %}
{% endblock content %}


{% block scripts %}
    <script src="{% static 'js/components/CardList.js' %}"></script>
    {% if user.is_authenticated %}
        <script src="{% static 'js/components/Favorites.js' %}"></script>
        <script src="{% static 'indexAuth.js' %}"></script>
    {% else %}
        <script src="{% static 'indexNotAuth.js' %}"></script>
    {% endif %}
{% endblock scripts %}

templates/recipes/profile.html
{% extends 'base.html' %}
{% load static %}
{% load user_filters %}

{% block title %}Рецепты | {{ author.get_full_name|default:author.username }}{% endblock title %}
{% block header_title %}{{ author.get_full_name|default:author.username }}{% endblock header_title %}

{% block content %}

{% if user.is_authenticated and author != user %}
    <div class="author-subscribe" data-author="{{ author.pk }}">
        <p style="padding: 0 0 2em 0;">
            {% include 'include/button_subscribe.html' %}
        </p>
    </div>
{% endif %}

<div class="card-list">
    {% for recipe in page_obj %}
        {% include 'include/recipe_card.html' %}
    {% endfor %}
</div>

{% if page_obj.has_other_pages %}
    {% include 'include/paginator.html' with page=page_obj paginator=paginator%}
{% endif %}
{% endblock content %}

{% block scripts %}
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
    <script src="{% static 'authorRecipe.js' %}"></script>
{% endblock scripts %}

templates/recipes/purchases.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Список покупок{% endblock %}
{% block css %}<link rel="stylesheet" href="{% static 'pages/shopList.css' %}">{% endblock css %}
{% block header_title %}Список покупок{% endblock header_title %}
{% block tags %}{% endblock %}

{% block content %}
    <div class="card-list card-list_column">
        <ul class="shopping-list">
            {% for recipe in object_list %}
                {% include 'include/recipe_purchases_preview.html' with recipe=recipe %}
            {% endfor %}
        </ul>

        {% if object_list.count %}
            <a href="{% url 'recipes:purchases_download' %}"><button class="button button_style_blue">Скачать список</button></a>
        {% endif %}
    </div>
{% endblock content %}

{% block scripts %}
    <script src="{% static 'js/components/ShopList.js' %}"></script>
    <script src="{% static 'shopList.js' %}"></script>
{% endblock scripts %}

templates/recipes/recipe.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}

{% block css %}
<link rel="stylesheet" href="{% static 'pages/single.css' %}">{% endblock css %}
{% block header %}{% endblock header %}

{% block content %}
<div class="single-card" data-id="{{ recipe.id }}" data-author="{{ recipe.author.id }}">
    {% thumbnail recipe.image "500x500" crop="center" upscale=True as im %}
    <img src="{{ im.url }}" alt="{{ recipe.title }}" class="single-card__image">
    {% endthumbnail %}
    <div class="single-card__info">
        <div class="single-card__header-info">
            <h1 class="single-card__title">{{ recipe.title }}</h1>
            {% if user.is_authenticated %}
            {% include 'include/button_favorite.html' with is_favorites=recipe.is_favorites big=True %}
            {% endif %}
        </div>
        <ul class="single-card__items">
            {% for tag in recipe.tags.all %}
            <li class="single-card__item"><span class="badge badge_style_{{ tag.color }}">
                    {{ tag.get_title_display }}</span></li>
            {% endfor %}
        </ul>
        <div class="single-card__items single-card__items_column">
            <p class="single-card__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
            {% if user.is_authenticated %}
            <ul class="single-card__items">
                <li class="single-card__item">
                    <p class="single-card__text">
                        <span class="icon-user"></span>
                        <a href="{% url 'recipes:profile' username=recipe.author.username %}" style="color: black">
                            {{ recipe.author.get_full_name|default:recipe.author.username }}</a>
                    </p>
                </li>
                {% if recipe.author == request.user or request.user.is_admin %}
                <li class="single-card__item"><a style="margin-left: 2.5em"
                        href="{% url 'recipes:recipe_edit' username=recipe.author.username pk=recipe.pk %}"
                        class="single-card__text">Редактировать рецепт</a></li>
                {% endif %}
            </ul>
            {% else %}
            <p class="single-card__text">
                <span class="icon-user"></span>
                <a href="{% url 'recipes:profile' username=recipe.author.username %}" style="color: black">
                    {{ recipe.author.get_full_name|default:recipe.author.username }}</a>
            </p>
            {% endif %}
        </div>

        {% if user.is_authenticated %}
        <ul class="single-card__items">
            <li class="single-card__item">
                {% include 'include/button_purchase.html' with is_purchase=recipe.is_purchase %}
            </li>
            {% include 'include/button_subscribe.html' with author=recipe.author %}
        </ul>
        {% endif %}

        <div class="single-card__section">
            <h3 class="single-card__section-title">Ингредиенты:</h3>
            <div class="single-card__items single-card__items_column">
                {% for ingredient in recipe.recipeingredient_set.all %}
                <p class=" single-card__section-item">{{ ingredient.ingredient.title }} - {{ ingredient.quantity }}
                    {{ ingredient.ingredient.dimension }}</p>
                {% endfor %}
            </div>
        </div>
        <div class="single-card__section">
            <h3 class="single-card__section-title">Описание:</h3>
            <p class=" single-card__section-text">{{ recipe.text }}</p>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script src="{% static 'js/components/SingleCard.js' %}"></script>
<script src="{% static 'js/components/CardList.js' %}"></script>

{% if user.is_authenticated %}
<script src="{% static 'js/components/Favorites.js' %}"></script>
<script src="{% static 'js/components/Subscribe.js' %}"></script>
<script src="{% static 'singlePage.js' %}"></script>
{% else %}
<script src="{% static 'singlePageNotAuth.js' %}"></script>
{% endif %}
{% endblock scripts %}

templates/recipes/recipe_confirm_delete.html
{% extends 'base.html' %}

{% block header %}{% endblock header %}
{% block tags %}{% endblock tags %}

{% block content %}
    <div class="custom-center-block">
        <p class="custom-text-block">Вы действительно хотите удалить рецепт "{{ object }}"?</p>
        <div class="custom-button-block">
            <form
                    action="{% url 'recipes:recipe_delete' recipe.author.username recipe.id %}"
                    method="post">
                {% csrf_token %}
                <button class="button button_style_blue" type="submit">Да</button>
                <a href="{% url 'recipes:purchases' %}" class="button">Назад к списку покупок</a></li>
            </form>
        </div>
    </div>
{% endblock content %}